# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The probabilities of each card coming next
#'
#' @param cards_remaining vector count of each type of card
#' @param dealer_card value of dealer's card showing
#' @return vector of probabilities
#' @export
nextCardProbs <- function(cards_remaining, dealer_card) {
    .Call(`_blackjack_nextCardProbs`, cards_remaining, dealer_card)
}

#' vector of probabilities for the 6 different dealer possibilities
#'
#' @param dealer_total dealer's total so far
#' @param cards_remaining vector count of each type of card
#' @param is_ace boolean indicating whether hand is soft
#' @param hit_soft_17 int (0 or 1) indicating dealer behaviour; defaults to true
#' @param is_first boolean indicating whether this is dealer's first unknown card
#' @return vector of probabilities (length 6)
#' @export
dealer <- function(dealer_total, cards_remaining, is_ace, hit_soft_17, is_first) {
    .Call(`_blackjack_dealer`, dealer_total, cards_remaining, is_ace, hit_soft_17, is_first)
}

